# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mortgageNumber', models.CharField(blank=True, default='', max_length=100)),
                ('fileCloseDate', models.DateTimeField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
